/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EstadoIncidencia = {
    Activa: 'ACTIVA',
    Resuelta: 'RESUELTA',
} as const;
export type EstadoIncidencia = typeof EstadoIncidencia[keyof typeof EstadoIncidencia];


export function instanceOfEstadoIncidencia(value: any): boolean {
    for (const key in EstadoIncidencia) {
        if (Object.prototype.hasOwnProperty.call(EstadoIncidencia, key)) {
            if (EstadoIncidencia[key as keyof typeof EstadoIncidencia] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EstadoIncidenciaFromJSON(json: any): EstadoIncidencia {
    return EstadoIncidenciaFromJSONTyped(json, false);
}

export function EstadoIncidenciaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EstadoIncidencia {
    return json as EstadoIncidencia;
}

export function EstadoIncidenciaToJSON(value?: EstadoIncidencia | null): any {
    return value as any;
}

export function EstadoIncidenciaToJSONTyped(value: any, ignoreDiscriminator: boolean): EstadoIncidencia {
    return value as EstadoIncidencia;
}

