/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { EstadoIncidencia } from './EstadoIncidencia';
import {
    EstadoIncidenciaFromJSON,
    EstadoIncidenciaFromJSONTyped,
    EstadoIncidenciaToJSON,
    EstadoIncidenciaToJSONTyped,
} from './EstadoIncidencia';

/**
 * 
 * @export
 * @interface Incidencia
 */
export interface Incidencia {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    titulo: string;
    /**
     * 
     */
    descripcion: string;
    /**
     * 
     */
    estado: EstadoIncidencia;
    /**
     * 
     */
    lineasAfectadas: Set<string>;
    /**
     * 
     */
    inicio: Date;
    /**
     * Fecha de finalización, cuando se conoce
     */
    fin?: Date;
}



/**
 * Check if a given object implements the Incidencia interface.
 */
export function instanceOfIncidencia(value: object): value is Incidencia {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('titulo' in value) || value['titulo'] === undefined) return false;
    if (!('descripcion' in value) || value['descripcion'] === undefined) return false;
    if (!('estado' in value) || value['estado'] === undefined) return false;
    if (!('lineasAfectadas' in value) || value['lineasAfectadas'] === undefined) return false;
    if (!('inicio' in value) || value['inicio'] === undefined) return false;
    return true;
}

export function IncidenciaFromJSON(json: any): Incidencia {
    return IncidenciaFromJSONTyped(json, false);
}

export function IncidenciaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Incidencia {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'titulo': json['titulo'],
        'descripcion': json['descripcion'],
        'estado': EstadoIncidenciaFromJSON(json['estado']),
        'lineasAfectadas': new Set(json['lineasAfectadas']),
        'inicio': (json['inicio'] == null ? json['inicio'] : parseDateTime(json['inicio'])),
        'fin': json['fin'] == null ? undefined : (parseDateTime(json['fin'])),
    };
}

export function IncidenciaToJSON(json: any): Incidencia {
    return IncidenciaToJSONTyped(json, false);
}

export function IncidenciaToJSONTyped(value?: Incidencia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'titulo': value['titulo'],
        'descripcion': value['descripcion'],
        'estado': EstadoIncidenciaToJSON(value['estado']),
        'lineasAfectadas': Array.from(value['lineasAfectadas'] as Set<any>),
        'inicio': value['inicio'] == null ? value['inicio'] : serializeDateTime(value['inicio']),
        'fin': value['fin'] == null ? value['fin'] : serializeDateTime(value['fin']),
    };
}

