/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModoTransporte } from './ModoTransporte';
import {
    ModoTransporteFromJSON,
    ModoTransporteFromJSONTyped,
    ModoTransporteToJSON,
    ModoTransporteToJSONTyped,
} from './ModoTransporte';

/**
 * 
 * @export
 * @interface Linea
 */
export interface Linea {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    nombre: string;
    /**
     * 
     */
    modo: ModoTransporte;
    /**
     * 
     */
    color: string;
    /**
     * 
     */
    origen: string;
    /**
     * 
     */
    destino: string;
}



/**
 * Check if a given object implements the Linea interface.
 */
export function instanceOfLinea(value: object): value is Linea {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    if (!('modo' in value) || value['modo'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('origen' in value) || value['origen'] === undefined) return false;
    if (!('destino' in value) || value['destino'] === undefined) return false;
    return true;
}

export function LineaFromJSON(json: any): Linea {
    return LineaFromJSONTyped(json, false);
}

export function LineaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Linea {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nombre': json['nombre'],
        'modo': ModoTransporteFromJSON(json['modo']),
        'color': json['color'],
        'origen': json['origen'],
        'destino': json['destino'],
    };
}

export function LineaToJSON(json: any): Linea {
    return LineaToJSONTyped(json, false);
}

export function LineaToJSONTyped(value?: Linea | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
        'modo': ModoTransporteToJSON(value['modo']),
        'color': value['color'],
        'origen': value['origen'],
        'destino': value['destino'],
    };
}

