/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface Llegada
 */
export interface Llegada {
    /**
     * 
     */
    servicioId: string;
    /**
     * 
     */
    lineaId: string;
    /**
     * 
     */
    destino: string;
    /**
     * 
     */
    horaProgramada: Date;
    /**
     * 
     */
    horaEstimada: Date;
    /**
     * Diferencia entre hora estimada y programada, redondeada a minutos.
     * Un valor negativo indica adelanto.
     * 
     */
    retrasoMinutos: number;
    /**
     * Indica si la estimación usa datos en tiempo real.
     * Si es false, se utiliza el horario programado.
     * 
     */
    tiempoReal: boolean;
}

/**
 * Check if a given object implements the Llegada interface.
 */
export function instanceOfLlegada(value: object): value is Llegada {
    if (!('servicioId' in value) || value['servicioId'] === undefined) return false;
    if (!('lineaId' in value) || value['lineaId'] === undefined) return false;
    if (!('destino' in value) || value['destino'] === undefined) return false;
    if (!('horaProgramada' in value) || value['horaProgramada'] === undefined) return false;
    if (!('horaEstimada' in value) || value['horaEstimada'] === undefined) return false;
    if (!('retrasoMinutos' in value) || value['retrasoMinutos'] === undefined) return false;
    if (!('tiempoReal' in value) || value['tiempoReal'] === undefined) return false;
    return true;
}

export function LlegadaFromJSON(json: any): Llegada {
    return LlegadaFromJSONTyped(json, false);
}

export function LlegadaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Llegada {
    if (json == null) {
        return json;
    }
    return {
        
        'servicioId': json['servicioId'],
        'lineaId': json['lineaId'],
        'destino': json['destino'],
        'horaProgramada': (json['horaProgramada'] == null ? json['horaProgramada'] : parseDateTime(json['horaProgramada'])),
        'horaEstimada': (json['horaEstimada'] == null ? json['horaEstimada'] : parseDateTime(json['horaEstimada'])),
        'retrasoMinutos': json['retrasoMinutos'],
        'tiempoReal': json['tiempoReal'],
    };
}

export function LlegadaToJSON(json: any): Llegada {
    return LlegadaToJSONTyped(json, false);
}

export function LlegadaToJSONTyped(value?: Llegada | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'servicioId': value['servicioId'],
        'lineaId': value['lineaId'],
        'destino': value['destino'],
        'horaProgramada': value['horaProgramada'] == null ? value['horaProgramada'] : serializeDateTime(value['horaProgramada']),
        'horaEstimada': value['horaEstimada'] == null ? value['horaEstimada'] : serializeDateTime(value['horaEstimada']),
        'retrasoMinutos': value['retrasoMinutos'],
        'tiempoReal': value['tiempoReal'],
    };
}

