/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     */
    codigo: string;
    /**
     * 
     */
    mensaje: string;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    if (!('codigo' in value) || value['codigo'] === undefined) return false;
    if (!('mensaje' in value) || value['mensaje'] === undefined) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'codigo': json['codigo'],
        'mensaje': json['mensaje'],
    };
}

export function ModelErrorToJSON(json: any): ModelError {
    return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(value?: ModelError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'codigo': value['codigo'],
        'mensaje': value['mensaje'],
    };
}

