/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ModoTransporte = {
    Metro: 'METRO',
    Autobus: 'AUTOBUS',
    Tranvia: 'TRANVIA',
} as const;
export type ModoTransporte = typeof ModoTransporte[keyof typeof ModoTransporte];


export function instanceOfModoTransporte(value: any): boolean {
    for (const key in ModoTransporte) {
        if (Object.prototype.hasOwnProperty.call(ModoTransporte, key)) {
            if (ModoTransporte[key as keyof typeof ModoTransporte] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ModoTransporteFromJSON(json: any): ModoTransporte {
    return ModoTransporteFromJSONTyped(json, false);
}

export function ModoTransporteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModoTransporte {
    return json as ModoTransporte;
}

export function ModoTransporteToJSON(value?: ModoTransporte | null): any {
    return value as any;
}

export function ModoTransporteToJSONTyped(value: any, ignoreDiscriminator: boolean): ModoTransporte {
    return value as ModoTransporte;
}

