/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Parada
 */
export interface Parada {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    nombre: string;
    /**
     * 
     */
    latitud: number;
    /**
     * 
     */
    longitud: number;
    /**
     * 
     */
    accesible: boolean;
    /**
     * 
     */
    lineas: Set<string>;
}

/**
 * Check if a given object implements the Parada interface.
 */
export function instanceOfParada(value: object): value is Parada {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    if (!('latitud' in value) || value['latitud'] === undefined) return false;
    if (!('longitud' in value) || value['longitud'] === undefined) return false;
    if (!('accesible' in value) || value['accesible'] === undefined) return false;
    if (!('lineas' in value) || value['lineas'] === undefined) return false;
    return true;
}

export function ParadaFromJSON(json: any): Parada {
    return ParadaFromJSONTyped(json, false);
}

export function ParadaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Parada {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nombre': json['nombre'],
        'latitud': json['latitud'],
        'longitud': json['longitud'],
        'accesible': json['accesible'],
        'lineas': new Set(json['lineas']),
    };
}

export function ParadaToJSON(json: any): Parada {
    return ParadaToJSONTyped(json, false);
}

export function ParadaToJSONTyped(value?: Parada | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
        'latitud': value['latitud'],
        'longitud': value['longitud'],
        'accesible': value['accesible'],
        'lineas': Array.from(value['lineas'] as Set<any>),
    };
}

