/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Parada } from './Parada';
import {
    ParadaFromJSON,
    ParadaFromJSONTyped,
    ParadaToJSON,
    ParadaToJSONTyped,
} from './Parada';

/**
 * 
 * @export
 * @interface ParadaEnLinea
 */
export interface ParadaEnLinea {
    /**
     * 
     */
    orden: number;
    /**
     * 
     */
    parada: Parada;
}

/**
 * Check if a given object implements the ParadaEnLinea interface.
 */
export function instanceOfParadaEnLinea(value: object): value is ParadaEnLinea {
    if (!('orden' in value) || value['orden'] === undefined) return false;
    if (!('parada' in value) || value['parada'] === undefined) return false;
    return true;
}

export function ParadaEnLineaFromJSON(json: any): ParadaEnLinea {
    return ParadaEnLineaFromJSONTyped(json, false);
}

export function ParadaEnLineaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParadaEnLinea {
    if (json == null) {
        return json;
    }
    return {
        
        'orden': json['orden'],
        'parada': ParadaFromJSON(json['parada']),
    };
}

export function ParadaEnLineaToJSON(json: any): ParadaEnLinea {
    return ParadaEnLineaToJSONTyped(json, false);
}

export function ParadaEnLineaToJSONTyped(value?: ParadaEnLinea | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orden': value['orden'],
        'parada': ParadaToJSON(value['parada']),
    };
}

