/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Tramo } from './Tramo';
import {
    TramoFromJSON,
    TramoFromJSONTyped,
    TramoToJSON,
    TramoToJSONTyped,
} from './Tramo';

/**
 * 
 * @export
 * @interface Ruta
 */
export interface Ruta {
    /**
     * 
     */
    salida: Date;
    /**
     * 
     */
    llegada: Date;
    /**
     * Duración total, incluyendo desplazamientos y esperas
     */
    duracionMinutos: number;
    /**
     * 
     */
    transbordos: number;
    /**
     * 
     */
    tramos: Array<Tramo>;
}

/**
 * Check if a given object implements the Ruta interface.
 */
export function instanceOfRuta(value: object): value is Ruta {
    if (!('salida' in value) || value['salida'] === undefined) return false;
    if (!('llegada' in value) || value['llegada'] === undefined) return false;
    if (!('duracionMinutos' in value) || value['duracionMinutos'] === undefined) return false;
    if (!('transbordos' in value) || value['transbordos'] === undefined) return false;
    if (!('tramos' in value) || value['tramos'] === undefined) return false;
    return true;
}

export function RutaFromJSON(json: any): Ruta {
    return RutaFromJSONTyped(json, false);
}

export function RutaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ruta {
    if (json == null) {
        return json;
    }
    return {
        
        'salida': (json['salida'] == null ? json['salida'] : parseDateTime(json['salida'])),
        'llegada': (json['llegada'] == null ? json['llegada'] : parseDateTime(json['llegada'])),
        'duracionMinutos': json['duracionMinutos'],
        'transbordos': json['transbordos'],
        'tramos': ((json['tramos'] as Array<any>).map(TramoFromJSON)),
    };
}

export function RutaToJSON(json: any): Ruta {
    return RutaToJSONTyped(json, false);
}

export function RutaToJSONTyped(value?: Ruta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'salida': value['salida'] == null ? value['salida'] : serializeDateTime(value['salida']),
        'llegada': value['llegada'] == null ? value['llegada'] : serializeDateTime(value['llegada']),
        'duracionMinutos': value['duracionMinutos'],
        'transbordos': value['transbordos'],
        'tramos': ((value['tramos'] as Array<any>).map(TramoToJSON)),
    };
}

