/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * IDA va del origen al destino de la línea; VUELTA, al contrario.
 * @export
 */
export const Sentido = {
    Ida: 'IDA',
    Vuelta: 'VUELTA',
} as const;
export type Sentido = typeof Sentido[keyof typeof Sentido];


export function instanceOfSentido(value: any): boolean {
    for (const key in Sentido) {
        if (Object.prototype.hasOwnProperty.call(Sentido, key)) {
            if (Sentido[key as keyof typeof Sentido] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SentidoFromJSON(json: any): Sentido {
    return SentidoFromJSONTyped(json, false);
}

export function SentidoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sentido {
    return json as Sentido;
}

export function SentidoToJSON(value?: Sentido | null): any {
    return value as any;
}

export function SentidoToJSONTyped(value: any, ignoreDiscriminator: boolean): Sentido {
    return value as Sentido;
}

