/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface Tramo
 */
export interface Tramo {
    /**
     * 
     */
    tipo: TramoTipoEnum;
    /**
     * Obligatorio para tramos de tipo TRANSPORTE
     */
    lineaId?: string;
    /**
     * 
     */
    origenId: string;
    /**
     * 
     */
    destinoId: string;
    /**
     * 
     */
    salida: Date;
    /**
     * 
     */
    llegada: Date;
}


/**
 * @export
 */
export const TramoTipoEnum = {
    Transporte: 'TRANSPORTE',
    APie: 'A_PIE',
} as const;
export type TramoTipoEnum = typeof TramoTipoEnum[keyof typeof TramoTipoEnum];


/**
 * Check if a given object implements the Tramo interface.
 */
export function instanceOfTramo(value: object): value is Tramo {
    if (!('tipo' in value) || value['tipo'] === undefined) return false;
    if (!('origenId' in value) || value['origenId'] === undefined) return false;
    if (!('destinoId' in value) || value['destinoId'] === undefined) return false;
    if (!('salida' in value) || value['salida'] === undefined) return false;
    if (!('llegada' in value) || value['llegada'] === undefined) return false;
    return true;
}

export function TramoFromJSON(json: any): Tramo {
    return TramoFromJSONTyped(json, false);
}

export function TramoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tramo {
    if (json == null) {
        return json;
    }
    return {
        
        'tipo': json['tipo'],
        'lineaId': json['lineaId'] == null ? undefined : json['lineaId'],
        'origenId': json['origenId'],
        'destinoId': json['destinoId'],
        'salida': (json['salida'] == null ? json['salida'] : parseDateTime(json['salida'])),
        'llegada': (json['llegada'] == null ? json['llegada'] : parseDateTime(json['llegada'])),
    };
}

export function TramoToJSON(json: any): Tramo {
    return TramoToJSONTyped(json, false);
}

export function TramoToJSONTyped(value?: Tramo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tipo': value['tipo'],
        'lineaId': value['lineaId'],
        'origenId': value['origenId'],
        'destinoId': value['destinoId'],
        'salida': value['salida'] == null ? value['salida'] : serializeDateTime(value['salida']),
        'llegada': value['llegada'] == null ? value['llegada'] : serializeDateTime(value['llegada']),
    };
}

