/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type EstadoIncidencia,
    EstadoIncidenciaFromJSON,
    EstadoIncidenciaToJSON,
} from '../models/EstadoIncidencia';
import {
    type Incidencia,
    IncidenciaFromJSON,
    IncidenciaToJSON,
} from '../models/Incidencia';

export interface ListarIncidenciasRequest {
    /**
     * 
     */
    lineaId?: string;
    /**
     * 
     */
    estado?: EstadoIncidencia;
}

/**
 * 
 */
export class IncidenciasApi extends runtime.BaseAPI {

    /**
     * Creates request options for listarIncidencias without sending the request
     */
    async listarIncidenciasRequestOpts(requestParameters: ListarIncidenciasRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lineaId'] != null) {
            queryParameters['lineaId'] = requestParameters['lineaId'];
        }

        if (requestParameters['estado'] != null) {
            queryParameters['estado'] = requestParameters['estado'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/incidencias`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar incidencias de la red
     */
    async listarIncidenciasRaw(requestParameters: ListarIncidenciasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Incidencia>>> {
        const requestOptions = await this.listarIncidenciasRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IncidenciaFromJSON));
    }

    /**
     * Consultar incidencias de la red
     */
    async listarIncidencias(requestParameters: ListarIncidenciasRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Incidencia>> {
        const response = await this.listarIncidenciasRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
