/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Linea,
    LineaFromJSON,
    LineaToJSON,
} from '../models/Linea';
import {
    type ModoTransporte,
    ModoTransporteFromJSON,
    ModoTransporteToJSON,
} from '../models/ModoTransporte';
import {
    type ParadaEnLinea,
    ParadaEnLineaFromJSON,
    ParadaEnLineaToJSON,
} from '../models/ParadaEnLinea';
import {
    type Sentido,
    SentidoFromJSON,
    SentidoToJSON,
} from '../models/Sentido';

export interface ListarLineasRequest {
    /**
     * Filtrar por medio de transporte
     */
    modo?: ModoTransporte;
}

export interface ListarParadasLineaRequest {
    /**
     * Identificador de la línea
     */
    lineaId: string;
    /**
     * 
     */
    sentido: Sentido;
}

export interface ObtenerLineaRequest {
    /**
     * Identificador de la línea
     */
    lineaId: string;
}

/**
 * 
 */
export class LneasApi extends runtime.BaseAPI {

    /**
     * Creates request options for listarLineas without sending the request
     */
    async listarLineasRequestOpts(requestParameters: ListarLineasRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['modo'] != null) {
            queryParameters['modo'] = requestParameters['modo'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/lineas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar las líneas de transporte
     */
    async listarLineasRaw(requestParameters: ListarLineasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Linea>>> {
        const requestOptions = await this.listarLineasRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LineaFromJSON));
    }

    /**
     * Consultar las líneas de transporte
     */
    async listarLineas(requestParameters: ListarLineasRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Linea>> {
        const response = await this.listarLineasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listarParadasLinea without sending the request
     */
    async listarParadasLineaRequestOpts(requestParameters: ListarParadasLineaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lineaId'] == null) {
            throw new runtime.RequiredError(
                'lineaId',
                'Required parameter "lineaId" was null or undefined when calling listarParadasLinea().'
            );
        }

        if (requestParameters['sentido'] == null) {
            throw new runtime.RequiredError(
                'sentido',
                'Required parameter "sentido" was null or undefined when calling listarParadasLinea().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sentido'] != null) {
            queryParameters['sentido'] = requestParameters['sentido'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/lineas/{lineaId}/paradas`;
        urlPath = urlPath.replace('{lineaId}', encodeURIComponent(String(requestParameters['lineaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar las paradas de una línea en orden de recorrido
     */
    async listarParadasLineaRaw(requestParameters: ListarParadasLineaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ParadaEnLinea>>> {
        const requestOptions = await this.listarParadasLineaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParadaEnLineaFromJSON));
    }

    /**
     * Consultar las paradas de una línea en orden de recorrido
     */
    async listarParadasLinea(requestParameters: ListarParadasLineaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ParadaEnLinea>> {
        const response = await this.listarParadasLineaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for obtenerLinea without sending the request
     */
    async obtenerLineaRequestOpts(requestParameters: ObtenerLineaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lineaId'] == null) {
            throw new runtime.RequiredError(
                'lineaId',
                'Required parameter "lineaId" was null or undefined when calling obtenerLinea().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/lineas/{lineaId}`;
        urlPath = urlPath.replace('{lineaId}', encodeURIComponent(String(requestParameters['lineaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar el detalle de una línea
     */
    async obtenerLineaRaw(requestParameters: ObtenerLineaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Linea>> {
        const requestOptions = await this.obtenerLineaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LineaFromJSON(jsonValue));
    }

    /**
     * Consultar el detalle de una línea
     */
    async obtenerLinea(requestParameters: ObtenerLineaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Linea> {
        const response = await this.obtenerLineaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
