/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Parada,
    ParadaFromJSON,
    ParadaToJSON,
} from '../models/Parada';
import {
    type ParadaEnLinea,
    ParadaEnLineaFromJSON,
    ParadaEnLineaToJSON,
} from '../models/ParadaEnLinea';
import {
    type Sentido,
    SentidoFromJSON,
    SentidoToJSON,
} from '../models/Sentido';

export interface BuscarParadasRequest {
    /**
     * Texto contenido en el nombre de la parada
     */
    nombre?: string;
    /**
     * Filtrar por accesibilidad
     */
    accesible?: boolean;
}

export interface ListarParadasLineaRequest {
    /**
     * Identificador de la línea
     */
    lineaId: string;
    /**
     * 
     */
    sentido: Sentido;
}

export interface ObtenerParadaRequest {
    /**
     * Identificador de la parada
     */
    paradaId: string;
}

/**
 * 
 */
export class ParadasApi extends runtime.BaseAPI {

    /**
     * Creates request options for buscarParadas without sending the request
     */
    async buscarParadasRequestOpts(requestParameters: BuscarParadasRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['nombre'] != null) {
            queryParameters['nombre'] = requestParameters['nombre'];
        }

        if (requestParameters['accesible'] != null) {
            queryParameters['accesible'] = requestParameters['accesible'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/paradas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Buscar paradas por nombre
     */
    async buscarParadasRaw(requestParameters: BuscarParadasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Parada>>> {
        const requestOptions = await this.buscarParadasRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParadaFromJSON));
    }

    /**
     * Buscar paradas por nombre
     */
    async buscarParadas(requestParameters: BuscarParadasRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Parada>> {
        const response = await this.buscarParadasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listarParadasLinea without sending the request
     */
    async listarParadasLineaRequestOpts(requestParameters: ListarParadasLineaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lineaId'] == null) {
            throw new runtime.RequiredError(
                'lineaId',
                'Required parameter "lineaId" was null or undefined when calling listarParadasLinea().'
            );
        }

        if (requestParameters['sentido'] == null) {
            throw new runtime.RequiredError(
                'sentido',
                'Required parameter "sentido" was null or undefined when calling listarParadasLinea().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sentido'] != null) {
            queryParameters['sentido'] = requestParameters['sentido'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/lineas/{lineaId}/paradas`;
        urlPath = urlPath.replace('{lineaId}', encodeURIComponent(String(requestParameters['lineaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar las paradas de una línea en orden de recorrido
     */
    async listarParadasLineaRaw(requestParameters: ListarParadasLineaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ParadaEnLinea>>> {
        const requestOptions = await this.listarParadasLineaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParadaEnLineaFromJSON));
    }

    /**
     * Consultar las paradas de una línea en orden de recorrido
     */
    async listarParadasLinea(requestParameters: ListarParadasLineaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ParadaEnLinea>> {
        const response = await this.listarParadasLineaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for obtenerParada without sending the request
     */
    async obtenerParadaRequestOpts(requestParameters: ObtenerParadaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paradaId'] == null) {
            throw new runtime.RequiredError(
                'paradaId',
                'Required parameter "paradaId" was null or undefined when calling obtenerParada().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/paradas/{paradaId}`;
        urlPath = urlPath.replace('{paradaId}', encodeURIComponent(String(requestParameters['paradaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar una parada
     */
    async obtenerParadaRaw(requestParameters: ObtenerParadaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Parada>> {
        const requestOptions = await this.obtenerParadaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ParadaFromJSON(jsonValue));
    }

    /**
     * Consultar una parada
     */
    async obtenerParada(requestParameters: ObtenerParadaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Parada> {
        const response = await this.obtenerParadaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
