/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Ruta,
    RutaFromJSON,
    RutaToJSON,
} from '../models/Ruta';

export interface CalcularRutasRequest {
    /**
     * 
     */
    origenId: string;
    /**
     * 
     */
    destinoId: string;
    /**
     * 
     */
    fechaHora?: Date;
    /**
     * 
     */
    soloAccesibles?: boolean;
    /**
     * 
     */
    maxTransbordos?: number;
}

/**
 * 
 */
export class RutasApi extends runtime.BaseAPI {

    /**
     * Creates request options for calcularRutas without sending the request
     */
    async calcularRutasRequestOpts(requestParameters: CalcularRutasRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['origenId'] == null) {
            throw new runtime.RequiredError(
                'origenId',
                'Required parameter "origenId" was null or undefined when calling calcularRutas().'
            );
        }

        if (requestParameters['destinoId'] == null) {
            throw new runtime.RequiredError(
                'destinoId',
                'Required parameter "destinoId" was null or undefined when calling calcularRutas().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['origenId'] != null) {
            queryParameters['origenId'] = requestParameters['origenId'];
        }

        if (requestParameters['destinoId'] != null) {
            queryParameters['destinoId'] = requestParameters['destinoId'];
        }

        if (requestParameters['fechaHora'] != null) {
            queryParameters['fechaHora'] = runtime.serializeDateTime(requestParameters['fechaHora'] as any);
        }

        if (requestParameters['soloAccesibles'] != null) {
            queryParameters['soloAccesibles'] = requestParameters['soloAccesibles'];
        }

        if (requestParameters['maxTransbordos'] != null) {
            queryParameters['maxTransbordos'] = requestParameters['maxTransbordos'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rutas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Devuelve alternativas ordenadas por duración total. Si no se indica fechaHora, se utiliza el momento de la consulta. Si no hay rutas disponibles, devuelve una lista vacía. 
     * Calcular rutas entre dos paradas
     */
    async calcularRutasRaw(requestParameters: CalcularRutasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Ruta>>> {
        const requestOptions = await this.calcularRutasRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RutaFromJSON));
    }

    /**
     * Devuelve alternativas ordenadas por duración total. Si no se indica fechaHora, se utiliza el momento de la consulta. Si no hay rutas disponibles, devuelve una lista vacía. 
     * Calcular rutas entre dos paradas
     */
    async calcularRutas(requestParameters: CalcularRutasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Ruta>> {
        const response = await this.calcularRutasRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
