/* tslint:disable */
/* eslint-disable */
/**
 * API de Transportes Metropolitanos
 * API de ejemplo para consultar la red de metro, autobús y tranvía. Los tiempos se expresan en minutos y las fechas en formato ISO 8601. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Llegada,
    LlegadaFromJSON,
    LlegadaToJSON,
} from '../models/Llegada';

export interface ConsultarLlegadasRequest {
    /**
     * Identificador de la parada
     */
    paradaId: string;
    /**
     * Filtrar las llegadas por línea
     */
    lineaId?: string;
    /**
     * 
     */
    limite?: number;
}

/**
 * 
 */
export class ServiciosApi extends runtime.BaseAPI {

    /**
     * Creates request options for consultarLlegadas without sending the request
     */
    async consultarLlegadasRequestOpts(requestParameters: ConsultarLlegadasRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paradaId'] == null) {
            throw new runtime.RequiredError(
                'paradaId',
                'Required parameter "paradaId" was null or undefined when calling consultarLlegadas().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lineaId'] != null) {
            queryParameters['lineaId'] = requestParameters['lineaId'];
        }

        if (requestParameters['limite'] != null) {
            queryParameters['limite'] = requestParameters['limite'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/paradas/{paradaId}/llegadas`;
        urlPath = urlPath.replace('{paradaId}', encodeURIComponent(String(requestParameters['paradaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar los próximos servicios de una parada
     */
    async consultarLlegadasRaw(requestParameters: ConsultarLlegadasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Llegada>>> {
        const requestOptions = await this.consultarLlegadasRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LlegadaFromJSON));
    }

    /**
     * Consultar los próximos servicios de una parada
     */
    async consultarLlegadas(requestParameters: ConsultarLlegadasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Llegada>> {
        const response = await this.consultarLlegadasRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
